import type { ListingProvider, NormalizedListing, SearchCriteria } from "./types";

const SAMPLE_AMENITIES = [
  ["gym", "in_unit_laundry", "parking", "wifi_included"],
  ["pool", "pet_friendly", "furnished", "study_room"],
  ["rooftop", "bike_storage", "ac", "dishwasher"],
  ["gym", "pet_friendly", "parking"],
];

/**
 * Deterministic fake listings, generated from the search criteria itself
 * (no network call, no API key). Used whenever a real provider isn't
 * configured, so local dev / CI / a fresh clone all work out of the box —
 * mirrors the "mock fallback when no API key" pattern used across the
 * project's other AI/data integrations.
 */
export const mockProvider: ListingProvider = {
  key: "mock",
  label: "Sample data (no provider configured)",
  isConfigured: () => true,
  async search(criteria: SearchCriteria): Promise<NormalizedListing[]> {
    const count = Math.min(criteria.limit ?? 8, 12);
    const hasCenter = criteria.lat != null && criteria.lng != null;
    const city = criteria.city ?? "Sample City";

    const listings: NormalizedListing[] = [];
    for (let i = 0; i < count; i++) {
      const priceSpread = criteria.maxPrice - (criteria.minPrice ?? Math.max(criteria.maxPrice - 800, 200));
      const price = Math.round((criteria.minPrice ?? Math.max(criteria.maxPrice - 800, 200)) + (priceSpread * i) / count);
      const amenities = SAMPLE_AMENITIES[i % SAMPLE_AMENITIES.length];
      const bedrooms = [0, 1, 1, 2, 2, 3][i % 6];

      listings.push({
        source: "mock",
        externalId: `mock-${city}-${i}`,
        title: `${bedrooms === 0 ? "Studio" : `${bedrooms}BR`} near ${city} #${i + 1}`,
        description:
          "Sample listing generated by the mock provider for local development. Configure a real ListingProvider (see lib/providers/README.md) to see live data.",
        url: "https://example.com/listing/mock-" + i,
        city,
        region: criteria.region,
        country: criteria.country,
        lat: hasCenter ? criteria.lat! + (Math.random() - 0.5) * 0.05 : undefined,
        lng: hasCenter ? criteria.lng! + (Math.random() - 0.5) * 0.05 : undefined,
        price: Math.max(price, 1),
        currency: criteria.currency ?? "USD",
        priceInterval: "month",
        bedrooms,
        bathrooms: Math.max(1, Math.floor(bedrooms / 2) + 1),
        amenities,
        petFriendly: amenities.includes("pet_friendly"),
        availableFrom: new Date(Date.now() + i * 3 * 24 * 60 * 60 * 1000),
        images: [],
        rating: 3.5 + (i % 5) * 0.3,
        reviewCount: 5 + i * 3,
      });
    }
    return listings;
  },
};
